Add check for unique email in db and add user values in profile page
Hexlet/hexlet-editor pull request #137
Opened 2022-10-12 16:16 UTC by LarendsD

1. Реализовал проверку уникальности E-mail при регистрации
2. Реализовал отображения данных о пользователе в профиле
3. Добавил дополнительно на стороне бекенда проверку на сравнение паролей
4. Сделал еще некоторые исправления, на которые ругался prettier(Извините не удержался :))

2022-10-12 16:26 UTC, LarendsD commented
@dzencot посмотри пожалуйста)

2022-10-13 18:53 UTC, dzencot requested changes

2022-10-13 18:53 UTC, dzencot commented on app/javascript/Pages/Profile.jsx
> +import Moment from 'moment';
moment вроде как [перестали поддерживать](https://momentjs.com/docs/#/-project-status/). Посмотри [Intl](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Intl) - может он покроет наши нужды, либо какую-то альтернативу.

2022-10-14 09:43 UTC, dzencot approved these changes

2022-10-14 09:44 UTC, merged