Add language slice and Select component
Hexlet/hexlet-editor pull request #54
Opened 2022-07-18 10:41 UTC by AndreiIlin

#23

2022-07-18 14:38 UTC, fey commented
Добрый день, падает сборка проекта. Давайте сперва попробуем исправить сборку, потом остальное.

2022-07-25 12:10 UTC, dzencot requested changes

2022-07-25 12:10 UTC, dzencot commented on package.json
> +    "react": "^17.0.2",
А чем обусловлен переход на предыдущую версию реакта? Это точно необходимо?

2022-07-25 12:10 UTC, dzencot commented on .github/workflows/pull-request.yml
> +      - name: Run __tests__
А это точно нужно переименовывать? Это же просто имя таска, он не должен привязываться к директории тестов

2022-07-25 12:10 UTC, dzencot commented on package.json
> +    "tsconfig-paths": "^3.14.1",
Тут тоже понижение версии. Это точно необходимо? По возможности лучше использовать последние версии либ, чтобы в будущем минимизировать проблемы с обновлениями.

2022-07-25 12:52 UTC, AndreiIlin commented on package.json
> +    "tsconfig-paths": "^3.14.1",
Это вообще не понимаю откуда, в текущей версии же стоит тоже 3.14.1

2022-07-25 12:54 UTC, AndreiIlin commented on .github/workflows/pull-request.yml
> +      - name: Run __tests__
Тут не обратил внимания, не знаю, это вебшторм подтянул изменения видимо. В ручную не переименовывал.

2022-07-25 12:59 UTC, AndreiIlin commented on package.json
> +    "react": "^17.0.2",
Эти изменения были приняты еще в предыдущем пулл-реквесте для сборки проекта, в этом из нового только слайс и компонент. Видимо из-за того что подтянул принятые изменения теперь все по новой отображает

2022-07-25 13:11 UTC, AndreiIlin commented on package.json
> +    "react": "^17.0.2",
Здесь почему то 2 коммита, отменить и направить pr по новой? или это можно как то исправить?

2022-07-27 06:37 UTC, dzencot commented on package.json
> +    "react": "^17.0.2",
Ок, тогда ладно.

2022-07-27 06:38 UTC, dzencot commented on .github/workflows/pull-request.yml
> +      - name: Run __tests__
Переименуй плз. Пусть будет tests

2022-07-27 06:39 UTC, dzencot commented on package.json
> +    "tsconfig-paths": "^3.14.1",
Ок

2022-07-27 11:46 UTC, AndreiIlin commented on .github/workflows/pull-request.yml
> +      - name: Run __tests__
Переименовал

2022-07-28 11:50 UTC, merged